# fly.toml app configuration file generated for notifyx

app = "notifyx"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  
  processes = ["app"]

[processes]
  # FastAPI API
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"

  # Celery worker 
  worker = "celery -A app.celery_app worker --loglevel=info --pool=solo"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
